services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - uploads:/app/uploads
      - data:/app/data
    env_file:
      - .env
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8501:8501'
    env_file:
      - .env
    environment:
      - API_URL=http://backend:8000
    depends_on:
      backend:
        condition: service_healthy

volumes:
  uploads:
  data: